import type { RedactionReport, RepoFacts } from "@prepo/shared";

/**
 * The Repo Card — pure stage-03 output, no model involved.
 *
 * It renders before any API key exists, which is deliberate: a new user sees
 * something real and correct about their repository in a few seconds, before
 * being asked to trust the application with a billable credential.
 */
export function RepoCard({
  facts,
  redaction,
}: {
  facts: RepoFacts;
  redaction: RedactionReport | null;
}) {
  const top = facts.languages.slice(0, 6);

  return (
    <section className="card">
      <div className="card-head">
        <span className="label">Repo card</span>
        <span className="small muted">parsed from the code — nothing here was generated by a model</span>
      </div>

      <div className="card-pad">
        <dl className="stats">
          <div className="stat">
            <dt>Files analysed</dt>
            <dd>
              {facts.analysedFileCount.toLocaleString()}
              <span className="unit">of {facts.fileCount.toLocaleString()}</span>
            </dd>
          </div>
          <div className="stat">
            <dt>Lines of code</dt>
            <dd>{facts.totalLoc.toLocaleString()}</dd>
          </div>
          <div className="stat">
            <dt>Commits</dt>
            <dd>
              {facts.git.commits.toLocaleString()}
              <span className="unit">{facts.git.contributors} authors</span>
            </dd>
          </div>
          <div className="stat">
            <dt>Routes</dt>
            <dd>{facts.routes.length}</dd>
          </div>
          <div className="stat">
            <dt>Tables</dt>
            <dd>{facts.tables.length}</dd>
          </div>
          <div className="stat">
            <dt>Tests</dt>
            <dd>{facts.testFileCount}</dd>
          </div>
        </dl>

        <div className="grid two" style={{ marginTop: "1.35rem" }}>
          <div>
            <div className="label">Languages</div>
            <div className="row" style={{ gap: ".3rem", marginTop: ".4rem" }}>
              {top.length === 0 && <span className="small muted">None detected</span>}
              {top.map((l) => (
                <span key={l.lang} className="chip">
                  {l.lang} {(l.share * 100).toFixed(0)}%
                </span>
              ))}
            </div>
          </div>

          <div>
            <div className="label">Frameworks</div>
            <div className="row" style={{ gap: ".3rem", marginTop: ".4rem" }}>
              {facts.frameworks.length === 0 && <span className="small muted">None detected</span>}
              {facts.frameworks.slice(0, 12).map((f) => (
                <span key={f} className="chip accent">
                  {f}
                </span>
              ))}
            </div>
          </div>
        </div>

        <div className="grid three" style={{ marginTop: "1.35rem" }}>
          <div>
            <div className="label">Deployment</div>
            <div className="row" style={{ gap: ".3rem", marginTop: ".4rem" }}>
              {facts.hasDockerfile && <span className="chip">Dockerfile</span>}
              {facts.hasCompose && <span className="chip">Compose</span>}
              {facts.ciProviders.map((c) => (
                <span key={c} className="chip">{c}</span>
              ))}
              {facts.iac.map((c) => (
                <span key={c} className="chip">{c}</span>
              ))}
              {!facts.hasDockerfile && facts.ciProviders.length === 0 && facts.iac.length === 0 && (
                <span className="small muted">None detected</span>
              )}
            </div>
          </div>

          <div>
            <div className="label">Entrypoints</div>
            <div className="mono muted" style={{ marginTop: ".4rem", fontSize: ".74rem" }}>
              {facts.entrypoints.length > 0 ? facts.entrypoints.slice(0, 4).join("  ·  ") : "None detected"}
            </div>
          </div>

          <div>
            <div className="label">Env surface</div>
            <div className="mono muted" style={{ marginTop: ".4rem", fontSize: ".74rem" }}>
              {facts.envVars.length > 0 ? `${facts.envVars.length} variables` : "None detected"}
            </div>
          </div>
        </div>

        {redaction && redaction.findings.length > 0 && (
          <div className="notice warn" style={{ marginTop: "1.35rem" }}>
            <span className="label">
              {redaction.findings.length} possible secret{redaction.findings.length === 1 ? "" : "s"} found and redacted
            </span>
            <p style={{ margin: ".3rem 0 .5rem" }}>
              These were replaced before anything was sent to a model. If any are live, rotate them.
            </p>
            <div className="mono" style={{ fontSize: ".72rem", display: "grid", gap: ".15rem" }}>
              {redaction.findings.slice(0, 8).map((f, i) => (
                <div key={i}>
                  {f.path}:{f.line} · {f.rule} · {f.preview}
                </div>
              ))}
              {redaction.findings.length > 8 && <div>… and {redaction.findings.length - 8} more</div>}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
